task: llm-sft
base_model: /home/jupyter/20000360102458359xu/LingfeiQian/saved_models/model_name
project_name: model_name_lr1e6_bs16
log: tensorboard
backend: local-cli

data:
  path: /home/jupyter/20000360102458359xu/LingfeiQian/saved_dataset/clinical_notes
  train_split: train
  valid_split: valid
  chat_template: chatml
  column_mapping:
    text_column: conversations

params:
  text_column: conversations

  block_size: 2048
  model_max_length: 2048

  epochs: 10
  batch_size: 16
  lr: 1e-6
  weight_decay: 0.1
  early_stopping: 1

  save_strategy: epoch
  save_total_limit: 20

  peft: true
  lora_r: 64
  lora_alpha: 128
  lora_dropout: 0.0
  quantization: int4
  target_modules: all-linear

  optimizer: adamw_torch
  scheduler: cosine
  gradient_accumulation: 1
  mixed_precision: bf16
  padding: right
